app = "your-app-name"  # Change this to a unique name
primary_region = "iad"  # Virginia (or choose closest: ord, dfw, etc.)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
